version: '3.9'

services:
  # Shared Services
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./shared/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      _LIMIT: 512M
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8088:80

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # App Services
  frontend_service:
    build:
      context: ./services/frontend_service
      dockerfile: Dockerfile
    container_name: frontend_service
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    volumes:
      - ./services/frontend_service:/rails
    ports:
      - "3000:3000"
    restart: unless-stopped

