version: '3.9'

services:
  # Shared Services
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./shared/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      _LIMIT: 512M
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8088:80

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./shared/elasticsearch:/usr/share/elasticsearch/data

  # App Services
  # auth_service:
  #   build:
  #     context: ./services/auth_service
  #   volumes:
  #     - ./services/auth_service:/app
  #   depends_on:
  #     - mysql
  #     - redis
  #   environment:
  #     DB_HOST: mysql
  #     DB_USERNAME: root
  #     DB_PASSWORD: password
  #   ports:
  #     - "3000:3000"

  # job_service:
  #   build:
  #     context: ./services/job_service
  #   volumes:
  #     - ./services/job_service:/app
  #   depends_on:
  #     - mysql
  #     - elasticsearch
  #   environment:
  #     DB_HOST: mysql
  #     DB_USERNAME: root
  #     DB_PASSWORD: password
  #   ports:
  #     - "3001:3001"

