version: '3.9'

services:
  # Shared Services
  mysql:
    image: mysql:8
    container_name: techbellys-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./shared/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: techbellys-phpmyadmin
    platform: linux/x86_64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
      _LIMIT: 512M
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8091:80

  redis:
    image: redis:7
    container_name: techbellys-redis
    ports:
      - "6389:6379"

  # App Services
  frontend_service:
    build:
      context: ./services/frontend_service
      dockerfile: Dockerfile
    container_name: techbellys-frontend_service
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${FRONTEND_RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${FRONTEND_SECRET_KEY_BASE}
    volumes:
      - ./services/frontend_service:/rails
    ports:
      - "4000:3000"
    restart: unless-stopped

  # # ✅ Auth API Rails App (API-only)
  auth_service:
    build:
      context: ./services/auth_service
      dockerfile: Dockerfile
    container_name: techbellys-auth_service
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${AUTH_SECRET_KEY_BASE}
      SECRET_KEY_BASE: ${AUTH_SECRET_KEY_BASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - ./services/auth_service:/rails
    ports:
      - "4001:3000"
    depends_on:
      - mysql
      - redis
    restart: unless-stopped


