default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DB_PORT", 3307) %>
  
development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "auth_service_development") %>

test:
  <<: *default
  database: auth_service_test

production:
  primary: &primary_production
    <<: *default
    database: auth_service_production
    username: auth_service
    password: <%= ENV["AUTH_SERVICE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: auth_service_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: auth_service_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: auth_service_production_cable
    migrations_paths: db/cable_migrate
